### ISSUE TITLE
Click on roll on font-color, close the window

### ISSUE THREAD

**Issue by Machou** [jordandelozier/wysibb#104]
Hello

if i click on scroll from font-color; close the window :s

Can you fix it please ?

https://i.imgur.com/aedBrTo.png

**Comment by Nikey646** [comment]
This appears to only occur in WebKit browsers from my testing. A quick fix, would be to add this css into a stylesheet somewhere. Warning: This could utterly break the editor for small screens and most definitely will if the width is not large enough to accommodate the entire editor and the toolbar.

```css
.wbb-list {
	overflow: hidden !important;
}
```

The way i see it, since the scrollbar doesn't appear in firefox and the colors line up perfectly, unlike in WebKit, this is more of a bug in WebKit then the wysiwyg editor.
